parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"wKTd":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.globalState=void 0,exports.globalState={currentFn:void 0,isQueueSleep:!0};
},{}],"mxom":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.useDependency=void 0;var e=require("./globalState");function n(){var n=new Set;return window.addEventListener("hashchange",function(){n.clear()}),{depend:function(){"function"==typeof e.globalState.currentFn&&n.add(e.globalState.currentFn)},notify:function(){n.forEach(function(e){return e()})}}}exports.useDependency=n;
},{"./globalState":"wKTd"}],"NvwB":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.nextTick=exports.add=void 0;var e=require("./globalState"),t=new Set;function o(o){t.has(o)||(t.add(o),e.globalState.isQueueSleep&&(e.globalState.isQueueSleep=!1,setTimeout(a,0)))}function a(){t.size&&(t.forEach(function(e){e()}),t.clear(),e.globalState.isQueueSleep=!0)}exports.add=o,exports.nextTick=a;
},{"./globalState":"wKTd"}],"WWYb":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.createState=void 0;var e=require("./dependency"),t=require("./asyncUpdateQueue");function r(r){var n=e.useDependency();return new Proxy(r,{get:function(e,t,r){return n.depend(),Reflect.get(e,t,r)},set:function(e,r,u,c){var a=Reflect.set(e,r,u,c);return t.add(n.notify),a}})}exports.createState=r;
},{"./dependency":"mxom","./asyncUpdateQueue":"NvwB"}],"v5qW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.createComponent=void 0;var e=require("./globalState");function t(t){e.globalState.currentFn=t,t(),e.globalState.currentFn=void 0}function o(e,o){var n=o();t(function(){document.querySelector(e).innerHTML="function"!=typeof n?n:n()})}exports.createComponent=o;
},{"./globalState":"wKTd"}],"kXwH":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.on=void 0;var e=[];function t(t){return{click:function(n){e.some(function(e){return e===n})||setTimeout(function(){return document.querySelector(t).addEventListener("click",n,!1)},0)},event:function(n,o){e.some(function(e){return e===o})||setTimeout(function(){return document.querySelector(t).addEventListener(n,o,!1)},0)},removeEvent:function(n,o){e.some(function(e){return e===o})||document.querySelector(t).removeEventListener(n,o,!1)}}}exports.on=t;
},{}],"dsxP":[function(require,module,exports) {
"use strict";function e(e){setTimeout(function(){e()},0)}Object.defineProperty(exports,"__esModule",{value:!0}),exports.onMounted=void 0,exports.onMounted=e;
},{}],"RIZW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.component=void 0;var e=require("./onMounted"),o=require("./createComponent");function n(n,t){e.onMounted(function(){o.createComponent(n,t)})}exports.component=n;
},{"./onMounted":"dsxP","./createComponent":"v5qW"}],"WxMs":[function(require,module,exports) {
"use strict";function e(e){window.addEventListener("hashchange",function n(o){e(),window.removeEventListener("hashchange",n,!1)},!1)}Object.defineProperty(exports,"__esModule",{value:!0}),exports.onUnmounted=void 0,exports.onUnmounted=e;
},{}],"N8lG":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.useRouter=exports.getParams=void 0;var t=require("./createComponent"),e=Object.create(null);function n(){return e}function r(){var n=Object.create(null);function r(){e={};for(var t=location.hash;t.startsWith("/")||t.startsWith("#");)t=t.substring(1);for(;t.endsWith("/");)t=t.substring(0,t.length-1);return t}function o(r,o){if("function"!=typeof n[r]){for(var i=function(i){if(i.includes(":")){var u=r.split("/"),s=i.split("/"),a=[];if(s.forEach(function(t,e){t.startsWith(":")&&a.push(e)}),a.forEach(function(t){u[t]=s[t]}),u.join("/")===i){var c=r.split("/");return a.forEach(function(t){e[s[t].substring(1)]=c[t]}),t.createComponent(o,n[i]),{value:void 0}}}if(i.endsWith("**")){var f=i.slice(0,-2);if(r.startsWith(f))return t.createComponent(o,n[i]),{value:void 0}}},u=0,s=Object.keys(n);u<s.length;u++){var a=i(s[u]);if("object"==typeof a)return a.value}"function"!=typeof n["*"]?t.createComponent(o,function(){return function(){return"<p>404 Not Found</p>"}}):t.createComponent(o,n["*"])}else t.createComponent(o,n[r])}return{route:function(t,e){for(;t.startsWith("/");)t=t.substring(1);n[t]=e},render:function(t){window.addEventListener("hashchange",function(){o(r(),t)},!1),o(r(),t)}}}exports.getParams=n,exports.useRouter=r;
},{"./createComponent":"v5qW"}],"JBW0":[function(require,module,exports) {
"use strict";function e(e){return new Proxy(e,{get:function(e,t,r){return Reflect.get(e,t,r)},set:function(e,t,r,n){return!1}})}Object.defineProperty(exports,"__esModule",{value:!0}),exports.readonly=void 0,exports.readonly=e;
},{}],"QCba":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./createState"),r=require("./createComponent"),t=require("./events"),n=require("./component"),o=require("./onMounted"),u=require("./onUnmounted"),a=require("./router"),d=require("./asyncUpdateQueue"),i=require("./readonly"),c={reactive:e.createState,render:r.createComponent,onMounted:o.onMounted,onUnmounted:u.onUnmounted,on:t.on,component:n.component,Router:{getParams:a.getParams,useRouter:a.useRouter},nextTick:d.nextTick,readonly:i.readonly};exports.default=c;
},{"./createState":"WWYb","./createComponent":"v5qW","./events":"kXwH","./component":"RIZW","./onMounted":"dsxP","./onUnmounted":"WxMs","./router":"N8lG","./asyncUpdateQueue":"NvwB","./readonly":"JBW0"}]},{},["QCba"], "ReOdd")